- hosts: "all"
  remote_user: "nonstandardusername"
  become: True
  vars:
    es_enable_xpack: False
    es_instance_name: "graylog"
    es_heap_size: "1g"
    es_config:
      node.name: "graylog"
      cluster.name: "graylog"
      http.port: 9200
      transport.tcp.port: 9300
      network.host: "127.0.0.1"
      node.data: True
      node.master: True
    graylog_install_java: False # Elasticsearch role already installed Java
    graylog_http_bind_address: "127.0.0.1:9000"
    graylog_http_publish_uri: "http://127.0.0.1:9000/"
    graylog_http_external_uri: "http://{{ inventory_hostname }}/"
    certbot_admin_email: "certbot@domain.com"
    graylog_server_version: "3.2.4-1"
    nginx_configs:
      ssl:
        - ssl_certificate_key "/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem"
        - ssl_certificate     "/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem"
        - ssl_dhparam         "/etc/ssl/dhparams.pem"
    nginx_sites:
      server:
        - "listen 80"
        - "server_name _"
        - "return 301 https://$host$request_uri"
      graylog:
        - listen 443 ssl http2
        - server_name {{ inventory_hostname }}
        - |
          location / {
            proxy_pass http://127.0.0.1:9000;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Graylog-Server-URL https://$server_name/;
          }
      apilogs:
        - listen 12201 ssl
        - server_name {{ inventory_hostname }}
        - |
          location /gelf {
            proxy_pass http://127.0.0.1:12001/gelf;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Graylog-Server-URL https://$server_name/gelf;
          }
      synclogs:
        - listen 12202 ssl
        - server_name {{ inventory_hostname }}
        - |
          location /gelf {
            proxy_pass http://127.0.0.1:12002/gelf;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Graylog-Server-URL https://$server_name/gelf;
          }
      weblogs:
        - listen 12203 ssl
        - server_name {{ inventory_hostname }}
        - |
          location /gelf {
            proxy_pass http://127.0.0.1:12003/gelf;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Server $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Graylog-Server-URL https://$server_name/gelf;
          }
  roles:
    - role: "certbot"
      tags:
        - "certbot"
    - role: "Graylog2.graylog-ansible-role"
      tags:
        - "graylog"