apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-deployment
  labels:
    app: projectworker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projectworker
  template:
    metadata:
      labels:
        app: projectworker
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
      - name: projectworker-container
        image: "#{registryUrl}#/#{imageRepository}#"
        imagePullPolicy: Always
        env:
        - name: "HOST_ENVIRONMENT"
          value: "Kubernetes"
        - name: "RUN_ENVIRONMENT"
          value: "#{runEnvironment}#"
        - name: "KEY_VAULT_URL"
          value: "#{keyVaultUrl}#"
        resources:
          limits:
            cpu: .5
            memory: 4096M
          requests:
            cpu: .1
            memory: 100M
        volumeMounts:
        - name: secrets
          mountPath: /app/secrets
          readOnly: true
        - name: appsettings-projectworker
          mountPath: /app/settings
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-appsettings
      - name: appsettings-projectworker
        configMap:
          name: appsettings-projectworker
