apiVersion: v1
kind: Secret
metadata:
  name: secret-appsettings
type: Opaque
stringData:
  appsettings.secrets.json: |-
    {
      "KeyVault": {
        "ClientId": "#{ProjectWorkerKeyVaultClientId}#",
        "Secret": "#{ProjectWorkerKeyVaultClientSecret}#"
      }
    }
